from .energy_forecast import ENERGY_FORECAST_PROMPT
from .trend_analysis import TREND_ANALYSIS_PROMPT
from .outlier_detection import OUTLIER_DETECTION_PROMPT
from .comparative_analysis import COMPARATIVE_ANALYSIS_PROMPT
from .time_comparative import TIME_COMPARATIVE_PROMPT
from .energy_efficiency import ENERGY_EFFICIENCY_EVALUATION_PROMPT
from .weather_energy_impact_forecast import WEATHER_ENERGY_IMPACT_FORECAST_PROMPT

__all__ = [
    'ENERGY_FORECAST_PROMPT',
    'TREND_ANALYSIS_PROMPT',
    'OUTLIER_DETECTION_PROMPT',
    'COMPARATIVE_ANALYSIS_PROMPT',
    'TIME_COMPARATIVE_PROMPT',
    'ENERGY_EFFICIENCY_EVALUATION_PROMPT',
    'WEATHER_ENERGY_IMPACT_FORECAST_PROMPT',
]